### PR TITLE
Fix summernote behave

### LINKED ISSUE #29: Form isn't submitted with enter key
When you hit enter on some field, the form isn't submitted.

The expected behave is to submit the form with the enter key.

Probably some problem with turbolinks.

### PR DESCRIPTION
**Pull request by duduribeiro**
Add a monkey patch to fix the summernote behave when an enter key is pressed outside the summernote's editor.
This bug is related to #29. 

Fixes #29 

-> i'm sending a beautiful photo of Salvador:

image

### CODE REVIEW

File: app/assets/javascripts/app.coffee [hunk 1]
```diff
@@ -0,0 +1,9 @@
+window.App ||= {}
+
+App.init = ->
+  $('[data-provider="summernote"]').each ->
+    $(this).summernote height: '400px'
+    return
+
+$(document).on "turbolinks:load", ->
+  App.init()
```
Comment (lastk) [inline app/assets/javascripts/app.coffee]: I would make it a little different and add `[data-provider="summernote"]` at `init` method. like so: 

`App.init('[data-provider="sumernote"]')`

also I think summernote should be its own component? so you would just initialize in the `#init` method?
```
App.init = ->
  SummerNote.init('[data-provider="summernote"]', '400px')
 ....
```

what do you think about it ?

File: app/assets/javascripts/pages/vacancies/new/new.coffee [hunk 2]
```diff
@@ -0,0 +1,14 @@
+App.Vacancies.New =
+  bind_fields: ->
+    $('#new_vacancy input').keypress (e) ->
```
Comment (lastk) [inline app/assets/javascripts/pages/vacancies/new/new.coffee]: same thing here, I would pass the selector instead of have it hardcoded here.

File: app/assets/javascripts/pages/vacancies/new/new.coffee [hunk 3]
```diff
@@ -0,0 +1,14 @@
...
+      if e.which == 13
+        $('#new_vacancy').submit()
+        return false
+
+$(document).on "turbolinks:load", ->
+  #TODO monkeypatch to allow the correct behave with summernote
+  # Remove when it will be fixed on summernote side
+
+  return unless $(".vacancies.new").length > 0 ||
+    $(".vacancies.create").length > 0
```
Comment (lastk) [inline app/assets/javascripts/pages/vacancies/new/new.coffee]: this logic shouldnt be inside the Vacancy component? like:
```
 $(document).on "turbolinks:load", ->
 return unless vacancies.has_vacancies? #dont mind the method name, im not sure what it is :P
````

File: app/views/layouts/application.html.erb [hunk 4]
```diff
@@ -11,7 +11,7 @@
 
   </head>
 
-  <body>
+  <body class="<%= controller_name %> <%= action_name %>">
```
Comment (lastk) [inline app/views/layouts/application.html.erb]: https://github.com/lucasmazza/page.js
you can use this guy to initialize your componentes for each page, I used it before and it was Pretty good.

File: app/assets/javascripts/app.coffee (hunk 1 above)
Comment (duduribeiro) [inline app/assets/javascripts/app.coffee]: This will be very nice.. Perfect idea. 💯

File: app/views/layouts/application.html.erb (hunk 4 above)
Comment (duduribeiro) [inline app/views/layouts/application.html.erb]: I will give it a try.

File: app/assets/javascripts/pages/vacancies/new/new.coffee (hunk 3 above)
Comment (duduribeiro) [inline app/assets/javascripts/pages/vacancies/new/new.coffee]: This logic is only for the `new` or `create` (rerendered) screen. Not all vacancies (it is only to fix the summernote behave). But I think we can move it to Summernote componente. What you think @lastk ?

File: app/assets/javascripts/pages/vacancies/new/new.coffee (hunk 2 above)
Comment (duduribeiro) [inline app/assets/javascripts/pages/vacancies/new/new.coffee]: And we pass use this selector on the constructor of the component?

File: app/assets/javascripts/pages/vacancies/new/new.coffee (hunk 3 above)
Comment (lastk) [inline app/assets/javascripts/pages/vacancies/new/new.coffee]: perfect ;)

File: app/assets/javascripts/pages/vacancies/new/new.coffee (hunk 2 above)
Comment (lastk) [inline app/assets/javascripts/pages/vacancies/new/new.coffee]: yeah! or even have default constructors, i dont remember if js has it right now, long time not doing frontend :(

**Comment by duduribeiro** [comment]
@lastk, moved the summernote initialization to a component object. With this, the javascript for new class could be removed. Can u check the changes plz?

🍻

**Comment by duduribeiro** [comment]
Merged 🚀
